Add IOSurface ColorAttachment kind
servo/surfman pull request #137
Opened 2019-06-04 14:31 UTC by zakorgy

Use IOSurfaces bound to textures as Framebuffer attachments, based on https://github.com/servo/rust-offscreen-rendering-context/pull/131.
We have three textures bound to IOSurfaces, one active (bound to the context),  one complete and one published to the WR thread. I found that using three IOSurfaces was the most more appropriate solution.
The body of `reset_draw_buffer_contents` is empty because that caused wrong background colors with https://github.com/servo/servo/pull/23509, I still need to figure out that part.

2019-06-04 14:50 UTC, jdm commented on src/draw_buffer.rs
> +                self.gl().bind_texture(gl::TEXTURE_2D, 0);
This should be TEXTURE_RECTANGLE.

2019-06-11 02:18 UTC, jdm requested changes
This looks ok, but we need to figure out the issue with reset_draw_buffer.

2019-06-11 02:18 UTC, jdm commented on src/draw_buffer.rs
> +use core_foundation::boolean::CFBoolean;
I would move most of these into the match arm that uses them, which will allow us to remove the #[cfg] attributes.

2019-06-11 02:18 UTC, jdm commented on src/lib.rs
> +extern crate io_surface;
This is missing a #[cfg] attribute.

2019-06-11 02:18 UTC, jdm commented on src/draw_buffer.rs
> +    IOSurface(([(GLuint, IOSurfaceID); SURFACE_COUNT], usize, usize, usize)),
We should really give these names:
```rust
IOSurface {
    surfaces: [(GLuint, IOSurfaceID); SURFACE_COUNT],
    sent: usize,
    complete: usize,
    active: usize,
}
```

2019-06-11 02:18 UTC, jdm commented on src/draw_buffer.rs
> +                    self.gl().bind_texture(gl::TEXTURE_2D, 0);
TEXTURE_RECTANGLE

2019-06-11 02:18 UTC, jdm commented on src/draw_buffer.rs
> +    pub fn swap_framebuffer_texture(&mut self) -> Option<IOSurfaceID> {
Missing #[cfg]

2019-06-11 02:18 UTC, jdm commented on src/draw_buffer.rs
> +    pub fn get_active_io_surface_id(&self) -> Option<IOSurfaceID> {
Missing #[cfg].

2019-06-11 09:01 UTC, zakorgy commented
@jdm I have mad ethe proposed changes, also changed the swap logic according to https://github.com/servo/servo/pull/23509#issuecomment-500597899. I still need to look into the `reset_draw_buffer` issue.

2019-06-11 13:05 UTC, zakorgy commented
Adding the `clear_color` value to `reset_draw_buffer_contents` fixes the background issue. Since the each WebGL context in Servo tracks his own `clear_color` value in [GLState](https://github.com/servo/servo/blob/b925c588014c9d4fa31cfa6fb09505a4173f9480/components/canvas/webgl_thread.rs#L27) we can pass it as a parameter when swapping buffers.

2019-06-11 14:12 UTC, jdm approved these changes

2019-06-24 13:34 UTC, jdm requested changes
We'll need to increase the Cargo version to 0.23 as well.

2019-06-24 13:34 UTC, jdm commented on src/gl_context.rs
> +    pub fn draw_buffer_is_bound(&self) -> bool {
This method is unused.

2019-06-24 13:34 UTC, jdm commented on src/draw_buffer.rs
> +    pub fn get_complete_io_surface_id(&self) -> Option<IOSurfaceID> {
This method is unused.

2019-07-17 10:54 UTC, zakorgy commented
This PR now depends on https://github.com/servo/core-foundation-rs/pull/324

2019-07-24 12:02 UTC, zakorgy commented
@jdm I have updated the PR and increased the crate version. Shall I squash the changes in one commit?

2019-07-24 13:47 UTC, jdm commented
Yes, go ahead.

2019-07-24 13:56 UTC, zakorgy commented
Squashed everything except the version bump commit.

2019-07-24 13:58 UTC, jdm commented
@bors-servo r+

2019-07-24 14:00 UTC, merged