use glow instead of gl_generator for GL/GLES bindings
servo/surfman pull request #321
Opened 2024-10-17 08:46 UTC by sagudev

see https://github.com/servo/servo/issues/33539

2024-11-29 18:51 UTC, sagudev commented
So the problem is that:
```rust
thread_local! {
    pub static GL_FUNCTIONS: Gl = unsafe {Gl::from_loader_function(context::get_proc_address)};
}
```
does not work because glow requires for context to be current, because it does some querying (version, extension). My idea is to simply replace all usages of `GL_FUNCTIONS` with `let gl = unsafe {Gl::from_loader_function(context::get_proc_address)};` as most of the time we are already current in the calls. This would make querying every time, but functions are not hot AFAIK, so this should be ok. Alternative would be to have Gl stored on context, but this needs to be lazy value, as context creation does not make context current.

2025-01-04 08:05 UTC, sagudev commented
I am wondering do we really need newly-created contexts that not immediately made current, or can we just made them current on creation? Linked issue on test is about something different. THis was introduced in https://github.com/servo/surfman/commit/dae72e4106028b002d5d41ed4bbe750d6c1b7d96. cc @pcwalton @jdm

2025-01-05 21:21 UTC, jdm commented
Original issue about inconsistent behavior: https://github.com/pcwalton/surfman/issues/7

2025-01-05 21:26 UTC, jdm commented
I believe we could change the behavior to always make new contexts current.

2025-01-06 09:54 UTC, sagudev commented
This is very close now, macos fails due to not clearing gl error before running create surface. Needs some cleanup (warnings) and updated servo companion PR.

2025-01-14 07:52 UTC, jdm commented
If you rebase this branch on top of https://github.com/servo/surfman/pull/326/ then the crash in https://github.com/servo/servo/pull/34328 will go away \o/

2025-01-14 08:28 UTC, mrobinson commented
Is this ready to be reviewed now?

2025-01-14 09:45 UTC, sagudev commented
> Is this ready to be reviewed now?

Yes

2025-01-14 10:08 UTC, mrobinson requested changes
Great stuff. I just have a few comments. In addition to what's below, please squash your changes into a single commit. Thank you!

2025-01-14 10:08 UTC, mrobinson commented on .gitignore
> +.vscode/settings.json
This should probably be a separate change and likely should be everything in the `.vscode` directory.

2025-01-14 10:08 UTC, mrobinson commented on android-example/app/src/androidTest/java/org/mozilla/surfmanthreadsexample/SurfmanInstrumentedTest.java
>      }
This seems to have the opposite meaning now, but the function name `newlyCreatedContextsAreNotCurrent` is the same.

2025-01-14 10:08 UTC, mrobinson commented on examples/threads.rs
>              };
This could use `map` and `ok` now.

2025-01-14 10:08 UTC, mrobinson commented on examples/threads.rs
> +                framebuffer_object.map(|fbo| fbo.0.get()).unwrap_or(0),
Perhaps use `map_or` here and other places this kind of thing is done.

2025-01-14 10:08 UTC, mrobinson commented on examples/offscreen.rs
> +        );
This could use `map_or`.

2025-01-14 10:08 UTC, mrobinson commented on src/context.rs
> +        gl.supported_extensions().contains("GL_ARB_compatibility")
Nice!

2025-01-14 10:08 UTC, mrobinson commented on src/info.rs
> +            minor: version.minor as u8,
Excellent to see this.

2025-01-14 10:08 UTC, mrobinson commented on src/platform/egl/surface/android_surface.rs
> +    pub fn surface_gl_texture_target(&self) -> u32 {
Gleam still has an `GLenum` type and it's defined as `c_uint`, so I'm curious why this is changing here? https://docs.rs/gleam/latest/gleam/gl/types/type.GLenum.html

2025-01-14 10:08 UTC, mrobinson commented on src/platform/generic/egl/surface.rs
> +            let texture_object = gl.create_texture().unwrap();
It would be nice to have error handling one day.

2025-01-14 10:08 UTC, mrobinson commented on src/platform/macos/cgl/context.rs
> +            return Err(Error::MakeCurrentFailed(err.to_windowing_api_error()));
```suggestion
        if CGLSetCurrentContext(cgl_context) != kCGLNoError {
            return Err(Error::MakeCurrentFailed(err.to_windowing_api_error()));
```

2025-01-14 10:08 UTC, mrobinson commented on src/platform/macos/cgl/context.rs
> +fn make_current(cgl_context: CGLContextObj) -> Result<(), Error> {
```suggestion
fn make_cgl_conetxt_current(cgl_context: CGLContextObj) -> Result<(), Error> {
```

2025-01-14 10:14 UTC, sagudev commented on .gitignore
> +.vscode/settings.json
I will remove this.

2025-01-14 10:50 UTC, sagudev commented on src/platform/generic/egl/surface.rs
> +            let texture_object = gl.create_texture().unwrap();
Actually to be compatible with old code it should be `.ok()` instead of unwrap.

2025-01-14 10:53 UTC, sagudev commented on src/platform/egl/surface/android_surface.rs
> +    pub fn surface_gl_texture_target(&self) -> u32 {
There is no gleam in surfman, but c_uint = u32 (most of the time).

2025-01-14 11:06 UTC, mrobinson commented on src/platform/egl/surface/android_surface.rs
> +    pub fn surface_gl_texture_target(&self) -> u32 {
Oh, of course. Thanks.

2025-01-14 11:07 UTC, sagudev commented on src/platform/macos/cgl/context.rs
> +            return Err(Error::MakeCurrentFailed(err.to_windowing_api_error()));
This won't work as we use err later.

2025-01-14 11:11 UTC, sagudev commented
> Great stuff. I just have a few comments. In addition to what's below, please squash your changes into a single commit. Thank you!

I will squash them before adding to queue.

2025-01-14 11:23 UTC, mrobinson approved these changes

2025-01-14 11:54 UTC, merged