Add android compilation to travis
servo/surfman pull request #96
Opened 2017-04-03 14:38 UTC by MortimerGoro

Add android compilation to travis

2017-04-03 14:57 UTC, emilio approved these changes
This is currently red, but thanks for this!

2017-04-03 14:57 UTC, emilio commented on .travis.yml
> +  - cargo build --verbose --target=arm-linux-androideabi
You probably need to `rustup install arm-linux-androideabi` before.

2017-04-03 14:57 UTC, emilio requested changes
Err, wrong checkbox.

2017-04-25 17:29 UTC, MortimerGoro commented
This was already fixed fixed.

2017-04-25 17:29 UTC, merged